### ISSUE TITLE
Zasek pri druhem cteni dat ze senzoru

### ISSUE THREAD

**Issue by dron23** [ivanahepjuk/SensoricNet-particle-meter#3]
Cau, sekne se to pri druhem cteni dat z BME280. Tady je aktualni debugovaci vystup. Dal uz to nenapise nic. 

```
Entering main loop.
Debug spike.
Wait.
Network connect.
Network connect done.
Enabling particlemeter.
Setting particlemeter fan.
Settings done.
New loop
Reading pm values
Reading BME280 values
Data: 26.580000, 973.080017, 0.000000, 0.000000, 0.000000, (null)
Encode values
Encoded data size: 34
Send encoded data
Sending done
Wait...
New loop
Reading pm values
Reading BME280 values
```

**Comment by dron23** [comment]
mam pocit, ze to ale dela to read_pm_values(); divne je, ze to zatuhne az potom...

**Comment by ivanahepjuk** [comment]
Jo vypada to ze read_pm _values nefunguje, nevim proc, jelo to okej ale tez mi to ted blbne.. Ten opcn2 je strasne citlivy na timing, chce to proskenovat logicou sondou co tam chodi.

**Comment by dron23** [comment]
tohle bylo zpusobeno inkludovanim spatnych specs pro semihosting. opraveno a uz vse funguje i se zaplym semihostingem.
